<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class PegawaiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('pegawais')->insert([[
            "nama_lengkap"  => "Anas Khoiri Abdillah",
            "npwp"  => "02.180.939.7-308.000",
            "jabatan_id"  => "1",
            "departemen_id"  => "14",
            "tgl_lahir"  => "2002-08-08",
            "jenis_kelamin"  => "Laki-laki",
            "alamat"  => "jalan Pemuda Ahmad No 17 Bangkalan",
            "no_telp"  => "083847086323",
            "email"  => "anaskhoiri19@gmail.com",
            "tgl_gabung"  => "2024-01-01",
            "status_id"  => "1",
            "pendidikan_id"  => "5",
            "nama_sekolah"  => "Universitas Trunojoyo Madura",
            "gaji"  => "10000000",
            "foto"  => "anas.jpg",
        ],[
            "nama_lengkap"  => "Anas Khoiri Abdillah",
            "npwp"  => "02.180.939.7-308.001",
            "jabatan_id"  => "2",
            "departemen_id"  => "14",
            "tgl_lahir"  => "2002-08-08",
            "jenis_kelamin"  => "Laki-laki",
            "alamat"  => "jalan Pemuda Ahmad No 17 Bangkalan",
            "no_telp"  => "083847086323",
            "email"  => "anaskhoiri19@gmail.com",
            "tgl_gabung"  => "2024-01-01",
            "status_id"  => "1",
            "pendidikan_id"  => "5",
            "nama_sekolah"  => "Universitas Trunojoyo Madura",
            "gaji"  => "10000000",
            "foto"  => "anas.jpg",
        ],[
            "nama_lengkap"  => "Anas Khoiri Abdillah",
            "npwp"  => "02.180.939.7-308.002",
            "jabatan_id"  => "3",
            "departemen_id"  => "2",
            "tgl_lahir"  => "2002-08-08",
            "jenis_kelamin"  => "Laki-laki",
            "alamat"  => "jalan Pemuda Ahmad No 17 Bangkalan",
            "no_telp"  => "083847086323",
            "email"  => "anaskhoiri19@gmail.com",
            "tgl_gabung"  => "2024-01-01",
            "status_id"  => "1",
            "pendidikan_id"  => "5",
            "nama_sekolah"  => "Universitas Trunojoyo Madura",
            "gaji"  => "10000000",
            "foto"  => "anas.jpg",
        ],[
            "nama_lengkap"  => "Anas Khoiri Abdillah",
            "npwp"  => "02.180.939.7-308.003",
            "jabatan_id"  => "4",
            "departemen_id"  => "5",
            "tgl_lahir"  => "2002-08-08",
            "jenis_kelamin"  => "Laki-laki",
            "alamat"  => "jalan Pemuda Ahmad No 17 Bangkalan",
            "no_telp"  => "083847086323",
            "email"  => "anaskhoiri19@gmail.com",
            "tgl_gabung"  => "2024-01-01",
            "status_id"  => "1",
            "pendidikan_id"  => "5",
            "nama_sekolah"  => "Universitas Trunojoyo Madura",
            "gaji"  => "10000000",
            "foto"  => "anas.jpg",
        ],[
            "nama_lengkap"  => "Anas Khoiri Abdillah",
            "npwp"  => "02.180.939.7-308.004",
            "jabatan_id"  => "5",
            "departemen_id"  => "3",
            "tgl_lahir"  => "2002-08-08",
            "jenis_kelamin"  => "Laki-laki",
            "alamat"  => "jalan Pemuda Ahmad No 17 Bangkalan",
            "no_telp"  => "083847086323",
            "email"  => "anaskhoiri19@gmail.com",
            "tgl_gabung"  => "2024-01-01",
            "status_id"  => "1",
            "pendidikan_id"  => "5",
            "nama_sekolah"  => "Universitas Trunojoyo Madura",
            "gaji"  => "10000000",
            "foto"  => "anas.jpg",
        ],[
            "nama_lengkap"  => "Anas Khoiri Abdillah",
            "npwp"  => "02.180.939.7-308.005",
            "jabatan_id"  => "6",
            "departemen_id"  => "1",
            "tgl_lahir"  => "2002-08-08",
            "jenis_kelamin"  => "Laki-laki",
            "alamat"  => "jalan Pemuda Ahmad No 17 Bangkalan",
            "no_telp"  => "083847086323",
            "email"  => "anaskhoiri19@gmail.com",
            "tgl_gabung"  => "2024-01-01",
            "status_id"  => "2",
            "pendidikan_id"  => "5",
            "nama_sekolah"  => "Universitas Trunojoyo Madura",
            "gaji"  => "10000000",
            "foto"  => "anas.jpg",
        ],[
            "nama_lengkap"  => "Anas Khoiri Abdillah",
            "npwp"  => "02.180.939.7-308.006",
            "jabatan_id"  => "7",
            "departemen_id"  => "14",
            "tgl_lahir"  => "2002-08-08",
            "jenis_kelamin"  => "Laki-laki",
            "alamat"  => "jalan Pemuda Ahmad No 17 Bangkalan",
            "no_telp"  => "083847086323",
            "email"  => "anaskhoiri19@gmail.com",
            "tgl_gabung"  => "2024-01-01",
            "status_id"  => "2",
            "pendidikan_id"  => "5",
            "nama_sekolah"  => "Universitas Trunojoyo Madura",
            "gaji"  => "10000000",
            "foto"  => "anas.jpg",
        ],[
            "nama_lengkap"  => "Anas Khoiri Abdillah",
            "npwp"  => "02.180.939.7-308.007",
            "jabatan_id"  => "8",
            "departemen_id"  => "14",
            "tgl_lahir"  => "2002-08-08",
            "jenis_kelamin"  => "Laki-laki",
            "alamat"  => "jalan Pemuda Ahmad No 17 Bangkalan",
            "no_telp"  => "083847086323",
            "email"  => "anaskhoiri19@gmail.com",
            "tgl_gabung"  => "2024-01-01",
            "status_id"  => "2",
            "pendidikan_id"  => "5",
            "nama_sekolah"  => "Universitas Trunojoyo Madura",
            "gaji"  => "10000000",
            "foto"  => "anas.jpg",
        ],[
            "nama_lengkap"  => "Anas Khoiri Abdillah",
            "npwp"  => "02.180.939.7-308.008",
            "jabatan_id"  => "9",
            "departemen_id"  => "2",
            "tgl_lahir"  => "2002-08-08",
            "jenis_kelamin"  => "Laki-laki",
            "alamat"  => "jalan Pemuda Ahmad No 17 Bangkalan",
            "no_telp"  => "083847086323",
            "email"  => "anaskhoiri19@gmail.com",
            "tgl_gabung"  => "2024-01-01",
            "status_id"  => "1",
            "pendidikan_id"  => "5",
            "nama_sekolah"  => "Universitas Trunojoyo Madura",
            "gaji"  => "10000000",
            "foto"  => "anas.jpg",
        ],[
            "nama_lengkap"  => "Anas Khoiri Abdillah",
            "npwp"  => "02.180.939.7-308.009",
            "jabatan_id"  => "10",
            "departemen_id"  => "1",
            "tgl_lahir"  => "2002-08-08",
            "jenis_kelamin"  => "Laki-laki",
            "alamat"  => "jalan Pemuda Ahmad No 17 Bangkalan",
            "no_telp"  => "083847086323",
            "email"  => "anaskhoiri19@gmail.com",
            "tgl_gabung"  => "2024-01-01",
            "status_id"  => "1",
            "pendidikan_id"  => "5",
            "nama_sekolah"  => "Universitas Trunojoyo Madura",
            "gaji"  => "10000000",
            "foto"  => "anas.jpg",
        ],[
            "nama_lengkap"  => "Anas Khoiri Abdillah",
            "npwp"  => "02.180.939.7-308.010",
            "jabatan_id"  => "11",
            "departemen_id"  => "1",
            "tgl_lahir"  => "2002-08-08",
            "jenis_kelamin"  => "Laki-laki",
            "alamat"  => "jalan Pemuda Ahmad No 17 Bangkalan",
            "no_telp"  => "083847086323",
            "email"  => "anaskhoiri19@gmail.com",
            "tgl_gabung"  => "2024-01-01",
            "status_id"  => "1",
            "pendidikan_id"  => "6",
            "nama_sekolah"  => "Universitas Trunojoyo Madura",
            "gaji"  => "10000000",
            "foto"  => "anas.jpg",
        ],[
            "nama_lengkap"  => "Anas Khoiri Abdillah",
            "npwp"  => "02.180.939.7-308.011",
            "jabatan_id"  => "12",
            "departemen_id"  => "4",
            "tgl_lahir"  => "2002-08-08",
            "jenis_kelamin"  => "Laki-laki",
            "alamat"  => "jalan Pemuda Ahmad No 17 Bangkalan",
            "no_telp"  => "083847086323",
            "email"  => "anaskhoiri19@gmail.com",
            "tgl_gabung"  => "2024-01-01",
            "status_id"  => "1",
            "pendidikan_id"  => "6",
            "nama_sekolah"  => "Universitas Trunojoyo Madura",
            "gaji"  => "10000000",
            "foto"  => "anas.jpg",
        ],[
            "nama_lengkap"  => "Anas Khoiri Abdillah",
            "npwp"  => "02.180.939.7-308.012",
            "jabatan_id"  => "13",
            "departemen_id"  => "5",
            "tgl_lahir"  => "2002-08-08",
            "jenis_kelamin"  => "Laki-laki",
            "alamat"  => "jalan Pemuda Ahmad No 17 Bangkalan",
            "no_telp"  => "083847086323",
            "email"  => "anaskhoiri19@gmail.com",
            "tgl_gabung"  => "2024-01-01",
            "status_id"  => "1",
            "pendidikan_id"  => "7",
            "nama_sekolah"  => "Universitas Trunojoyo Madura",
            "gaji"  => "10000000",
            "foto"  => "anas.jpg",
        ],[
            "nama_lengkap"  => "Anas Khoiri Abdillah",
            "npwp"  => "02.180.939.7-308.013",
            "jabatan_id"  => "14",
            "departemen_id"  => "5",
            "tgl_lahir"  => "2002-08-08",
            "jenis_kelamin"  => "Laki-laki",
            "alamat"  => "jalan Pemuda Ahmad No 17 Bangkalan",
            "no_telp"  => "083847086323",
            "email"  => "anaskhoiri19@gmail.com",
            "tgl_gabung"  => "2024-01-01",
            "status_id"  => "3",
            "pendidikan_id"  => "1",
            "nama_sekolah"  => "Universitas Trunojoyo Madura",
            "gaji"  => "10000000",
            "foto"  => "anas.jpg",
        ],[
            "nama_lengkap"  => "Anas Khoiri Abdillah",
            "npwp"  => "02.180.939.7-308.014",
            "jabatan_id"  => "15",
            "departemen_id"  => "5",
            "tgl_lahir"  => "2002-08-08",
            "jenis_kelamin"  => "Laki-laki",
            "alamat"  => "jalan Pemuda Ahmad No 17 Bangkalan",
            "no_telp"  => "083847086323",
            "email"  => "anaskhoiri19@gmail.com",
            "tgl_gabung"  => "2024-01-01",
            "status_id"  => "3",
            "pendidikan_id"  => "1",
            "nama_sekolah"  => "Universitas Trunojoyo Madura",
            "gaji"  => "10000000",
            "foto"  => "anas.jpg",
        ],[
            "nama_lengkap"  => "Anas Khoiri Abdillah",
            "npwp"  => "02.180.939.7-308.015",
            "jabatan_id"  => "16",
            "departemen_id"  => "2",
            "tgl_lahir"  => "2002-08-08",
            "jenis_kelamin"  => "Laki-laki",
            "alamat"  => "jalan Pemuda Ahmad No 17 Bangkalan",
            "no_telp"  => "083847086323",
            "email"  => "anaskhoiri19@gmail.com",
            "tgl_gabung"  => "2024-01-01",
            "status_id"  => "3",
            "pendidikan_id"  => "6",
            "nama_sekolah"  => "Universitas Trunojoyo Madura",
            "gaji"  => "10000000",
            "foto"  => "anas.jpg",
        ],[
            "nama_lengkap"  => "Anas Khoiri Abdillah",
            "npwp"  => "02.180.939.7-308.016",
            "jabatan_id"  => "17",
            "departemen_id"  => "1",
            "tgl_lahir"  => "2002-08-08",
            "jenis_kelamin"  => "Laki-laki",
            "alamat"  => "jalan Pemuda Ahmad No 17 Bangkalan",
            "no_telp"  => "083847086323",
            "email"  => "anaskhoiri19@gmail.com",
            "tgl_gabung"  => "2024-01-01",
            "status_id"  => "3",
            "pendidikan_id"  => "3",
            "nama_sekolah"  => "Universitas Trunojoyo Madura",
            "gaji"  => "10000000",
            "foto"  => "anas.jpg",
        ],[
            "nama_lengkap"  => "Anas Khoiri Abdillah",
            "npwp"  => "02.180.939.7-308.017",
            "jabatan_id"  => "18",
            "departemen_id"  => "3",
            "tgl_lahir"  => "2002-08-08",
            "jenis_kelamin"  => "Laki-laki",
            "alamat"  => "jalan Pemuda Ahmad No 17 Bangkalan",
            "no_telp"  => "083847086323",
            "email"  => "anaskhoiri19@gmail.com",
            "tgl_gabung"  => "2024-01-01",
            "status_id"  => "3",
            "pendidikan_id"  => "3",
            "nama_sekolah"  => "Universitas Trunojoyo Madura",
            "gaji"  => "10000000",
            "foto"  => "anas.jpg",
        ],[
            "nama_lengkap"  => "Anas Khoiri Abdillah",
            "npwp"  => "02.180.939.7-308.018",
            "jabatan_id"  => "19",
            "departemen_id"  => "4",
            "tgl_lahir"  => "2002-08-08",
            "jenis_kelamin"  => "Laki-laki",
            "alamat"  => "jalan Pemuda Ahmad No 17 Bangkalan",
            "no_telp"  => "083847086323",
            "email"  => "anaskhoiri19@gmail.com",
            "tgl_gabung"  => "2024-01-01",
            "status_id"  => "3",
            "pendidikan_id"  => "3",
            "nama_sekolah"  => "Universitas Trunojoyo Madura",
            "gaji"  => "10000000",
            "foto"  => "anas.jpg",
        ],[
            "nama_lengkap"  => "Anas Khoiri Abdillah",
            "npwp"  => "02.180.939.7-308.019",
            "jabatan_id"  => "20",
            "departemen_id"  => "9",
            "tgl_lahir"  => "2002-08-08",
            "jenis_kelamin"  => "Laki-laki",
            "alamat"  => "jalan Pemuda Ahmad No 17 Bangkalan",
            "no_telp"  => "083847086323",
            "email"  => "anaskhoiri19@gmail.com",
            "tgl_gabung"  => "2024-01-01",
            "status_id"  => "3",
            "pendidikan_id"  => "2",
            "nama_sekolah"  => "Universitas Trunojoyo Madura",
            "gaji"  => "10000000",
            "foto"  => "anas.jpg",
        ],[
            "nama_lengkap"  => "Anas Khoiri Abdillah",
            "npwp"  => "02.180.939.7-308.020",
            "jabatan_id"  => "21",
            "departemen_id"  => "12",
            "tgl_lahir"  => "2002-08-08",
            "jenis_kelamin"  => "Laki-laki",
            "alamat"  => "jalan Pemuda Ahmad No 17 Bangkalan",
            "no_telp"  => "083847086323",
            "email"  => "anaskhoiri19@gmail.com",
            "tgl_gabung"  => "2024-01-01",
            "status_id"  => "3",
            "pendidikan_id"  => "2",
            "nama_sekolah"  => "Universitas Trunojoyo Madura",
            "gaji"  => "10000000",
            "foto"  => "anas.jpg",
        ]]);
    }
}
